# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DeterminantMicroBlazeRecording/Nexys4ddrMaster.xdc

# Block Designs: bd/DeterminantMicroBlaze/DeterminantMicroBlaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze || ORIG_REF_NAME==DeterminantMicroBlaze} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_clk_wiz_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_DeterminantTopModule_0_0/DeterminantMicroBlaze_DeterminantTopModule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_DeterminantTopModule_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_DeterminantTopModule_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_uartlite_0_0/DeterminantMicroBlaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_0_0/DeterminantMicroBlaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_1_0/DeterminantMicroBlaze_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_1_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_2_0/DeterminantMicroBlaze_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_2_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_2_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_0/DeterminantMicroBlaze_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_4_0/DeterminantMicroBlaze_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_4_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_4_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_5_0/DeterminantMicroBlaze_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_5_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_5_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_6_0/DeterminantMicroBlaze_axi_gpio_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_6_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_6_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_7_0/DeterminantMicroBlaze_axi_gpio_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_7_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_7_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_8_0/DeterminantMicroBlaze_axi_gpio_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_8_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_8_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_9_0/DeterminantMicroBlaze_axi_gpio_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_9_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_9_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_microblaze_0_0/DeterminantMicroBlaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_microblaze_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_microblaze_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_dlmb_v10_0/DeterminantMicroBlaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_dlmb_v10_0 || ORIG_REF_NAME==DeterminantMicroBlaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_ilmb_v10_0/DeterminantMicroBlaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_ilmb_v10_0 || ORIG_REF_NAME==DeterminantMicroBlaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_dlmb_bram_if_cntlr_0/DeterminantMicroBlaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DeterminantMicroBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_ilmb_bram_if_cntlr_0/DeterminantMicroBlaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DeterminantMicroBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_lmb_bram_0/DeterminantMicroBlaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_lmb_bram_0 || ORIG_REF_NAME==DeterminantMicroBlaze_lmb_bram_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_mdm_1_0/DeterminantMicroBlaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_mdm_1_0 || ORIG_REF_NAME==DeterminantMicroBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_rst_clk_wiz_0_100M_0/DeterminantMicroBlaze_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==DeterminantMicroBlaze_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_xbar_0/DeterminantMicroBlaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_xbar_0 || ORIG_REF_NAME==DeterminantMicroBlaze_xbar_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_microblaze_0_axi_periph_0/DeterminantMicroBlaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DeterminantMicroBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_util_vector_logic_0_0/DeterminantMicroBlaze_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_util_vector_logic_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_timer_0_0/DeterminantMicroBlaze_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_timer_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_timer_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_10_0/DeterminantMicroBlaze_axi_gpio_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_10_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_10_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_11_0/DeterminantMicroBlaze_axi_gpio_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_11_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_11_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_12_0/DeterminantMicroBlaze_axi_gpio_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_12_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_12_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_13_0/DeterminantMicroBlaze_axi_gpio_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_13_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_13_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_14_0/DeterminantMicroBlaze_axi_gpio_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_14_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_14_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_15_0/DeterminantMicroBlaze_axi_gpio_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_15_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_15_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_16_0/DeterminantMicroBlaze_axi_gpio_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_16_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_16_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_17_0/DeterminantMicroBlaze_axi_gpio_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_17_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_17_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_18_0/DeterminantMicroBlaze_axi_gpio_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_18_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_18_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_19_0/DeterminantMicroBlaze_axi_gpio_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_19_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_19_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_20_0/DeterminantMicroBlaze_axi_gpio_20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_20_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_20_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_21_0/DeterminantMicroBlaze_axi_gpio_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_21_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_21_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_22_0/DeterminantMicroBlaze_axi_gpio_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_22_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_22_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_23_0/DeterminantMicroBlaze_axi_gpio_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_23_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_23_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_24_0/DeterminantMicroBlaze_axi_gpio_24_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_24_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_24_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_25_0/DeterminantMicroBlaze_axi_gpio_25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_25_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_25_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_26_0/DeterminantMicroBlaze_axi_gpio_26_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_26_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_26_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_27_0/DeterminantMicroBlaze_axi_gpio_27_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_27_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_27_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_28_1/DeterminantMicroBlaze_axi_gpio_28_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_28_1 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_28_1} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_29_0/DeterminantMicroBlaze_axi_gpio_29_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_29_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_29_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_tier2_xbar_0_0/DeterminantMicroBlaze_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_tier2_xbar_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_tier2_xbar_1_0/DeterminantMicroBlaze_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_tier2_xbar_1_0 || ORIG_REF_NAME==DeterminantMicroBlaze_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_tier2_xbar_2_0/DeterminantMicroBlaze_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_tier2_xbar_2_0 || ORIG_REF_NAME==DeterminantMicroBlaze_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_tier2_xbar_3_0/DeterminantMicroBlaze_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_tier2_xbar_3_0 || ORIG_REF_NAME==DeterminantMicroBlaze_tier2_xbar_3_0} -quiet] -quiet

# XDC: bd/DeterminantMicroBlaze/DeterminantMicroBlaze_ooc.xdc
